import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, Section, SUPPORT_EMAIL } from "@/components/cyber/Legal";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Unbluff" },
      {
        name: "description",
        content: "The rules for using Unbluff's AI message decoder and decode credits.",
      },
      { property: "og:title", content: "Terms of Service — Unbluff" },
      { property: "og:description", content: "Rules for using Unbluff and its decode credits." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Terms,
});

function Terms() {
  return (
    <LegalPage title="Terms of Service" updated="12 August 2026">
      <p>
        These Terms govern your use of Unbluff (the "Service"), an AI tool that analyses messages
        you submit and drafts suggested replies. By creating an account or purchasing decode
        credits, you agree to these Terms.
      </p>
      <Section heading="1. The service">
        Unbluff analyses text or screenshots you paste and returns an interpretation of tone,
        possible manipulation patterns and suggested replies. Output is generated by AI, may be
        inaccurate, and is provided for informational purposes only. It is not legal, medical,
        psychological, HR or financial advice, and it is not a lie detector or a factual
        determination about any person.
      </Section>
      <Section heading="2. Accounts">
        You must be at least 18 years old and provide accurate account details. You are responsible
        for activity under your account and for keeping your login secure.
      </Section>
      <Section heading="3. Decode credits">
        The Service is sold as one-time credit packs, not a subscription. Each decode consumes one
        credit. Credits are prepaid, tied to your account, non-transferable, and have no cash value.
        Prices are shown before purchase and may include tax depending on your location. Credits do
        not expire while your account remains active.
      </Section>
      <Section heading="4. Acceptable use">
        <p>You agree not to use the Service to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>harass, stalk, threaten, defame or manipulate another person;</li>
          <li>upload content you have no right to share, or sensitive data about third parties;</li>
          <li>attempt to reverse engineer, scrape, resell or overload the Service;</li>
          <li>break any applicable law.</li>
        </ul>
        <p>We may suspend accounts that violate these rules.</p>
      </Section>
      <Section heading="5. Your content">
        You keep ownership of the messages you submit and of the generated replies. You grant us a
        limited licence to process your content in order to deliver the Service. See the Privacy
        Policy for how content is stored.
      </Section>
      <Section heading="6. Availability and liability">
        The Service is provided "as is" without warranties. To the maximum extent permitted by law,
        our total liability for any claim is limited to the amount you paid us in the 12 months
        before the claim. Nothing here limits rights you have as a consumer that cannot be waived.
      </Section>
      <Section heading="7. Changes and termination">
        We may update these Terms; material changes will be reflected in the "last updated" date.
        You may stop using the Service at any time and request account deletion. Unused credits are
        handled under the Refund Policy.
      </Section>
      <Section heading="8. Contact">
        Questions about these Terms: <span className="text-neon">{SUPPORT_EMAIL}</span>
      </Section>
    </LegalPage>
  );
}